python -u main_rlrop.py --arch vgg19 --dataset data --test_id 00 --outdir results/vgg19/00 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 01 --outdir results/vgg19/01 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 02 --outdir results/vgg19/02 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 03 --outdir results/vgg19/03 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 04 --outdir results/vgg19/04 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 05 --outdir results/vgg19/05 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 06 --outdir results/vgg19/06 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters                
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 07 --outdir results/vgg19/07 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters                
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 08 --outdir results/vgg19/08 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters                
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 09 --outdir results/vgg19/09 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 10 --outdir results/vgg19/10 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters              
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 11 --outdir results/vgg19/11 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters                
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 12 --outdir results/vgg19/12 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters                
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 13 --outdir results/vgg19/13 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters                
                                                                                                                                                                                                            
python -u main_rlrop.py --arch vgg19 --dataset data --test_id 14 --outdir results/vgg19/14 --batch_size 128 --epochs 40 --patience 2 --verbose True --factor 0.5 --tensorboard --tensorboard_images --tensorboard_parameters
